version: "2"
linters:
  default: standard
  enable:
    - bidichk
    - errcheck
    - bodyclose
    - canonicalheader
    - copyloopvar
    - decorder
    - dogsled
    - errchkjson
    - errorlint
    - errname
    - exptostd
    - gosec
    - loggercheck
    - misspell
    - musttag
  exclusions:
    generated: strict
formatters:
  enable:
    - gofmt
  exclusions:
    generated: strict
