version: '3'
services:
  # This is a copy of the docker compose from the conformance suite repository
  # with some changes that allow the suite to call an authorization server running
  # on localhost.
  # The auth server is expected to be running under the domain "auth.localhost".
  mongodb:
    image: mongo:5.0.24
  httpd:
    build:
      context: ./conformance-suite/httpd
      dockerfile: Dockerfile-static
    ports:
     - "8443:8443"
     - "8444:8444"
    volumes:
     - ./conformance-suite/src/main/resources/:/usr/local/apache2/htdocs/
    depends_on:
     - server
  server:
    build:
      context: ./conformance-suite/server-dev
    ports:
     - "9999:9999"
    volumes:
     - ./conformance-suite/target/:/server/
    command: >
      java
      -Xdebug -Xrunjdwp:transport=dt_socket,address=*:9999,server=y,suspend=n
      -jar /server/fapi-test-suite.jar
      -Djdk.tls.maxHandshakeMessageSize=65536
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.base_mtls_url=https://localhost.emobix.co.uk:8444
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true
    links:
     - mongodb:mongodb
    depends_on:
     - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
    extra_hosts:
      # Requests to auth.localhost and matls-auth.localhost are forwarded to the
      # docker host where the authorization server is running.
      - auth.localhost:host-gateway
      - matls-auth.localhost:host-gateway
