package authorize

var ValidateAuthorizationRequest = validateAuthorizationRequest
var ValidateAuthorizationRequestWithPAR = validateAuthzRequestWithPAR
var ValidateAuthorizationRequestWithJAR = validateAuthzRequestWithJAR
