package authorize

var ValidateAuthorizationRequest = validateAuthorizationRequest
var ValidateAuthorizationRequestWithPar = validateAuthorizationRequestWithPar
var ValidateAuthorizationRequestWithJar = validateAuthorizationRequestWithJar
