package authorize

var ValidateAuthorizationRequest = validateAuthzRequest
var ValidateAuthorizationRequestWithPAR = validateAuthzRequestWithPAR
var ValidateAuthorizationRequestWithJAR = validateAuthzRequestWithJAR
